# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 05:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created_time',
            new_name='pubtime',
        ),
    ]
