# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-01 07:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_auto_20180131_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='news_profile',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.news')),
                ('viewed_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('liked_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('collected_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='news_tag_score',
            fields=[
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.news')),
                ('news_society', models.FloatField(blank=True, null=True)),
                ('news_tech', models.FloatField(blank=True, null=True)),
                ('news_entertainment', models.FloatField(blank=True, null=True)),
                ('news_game', models.FloatField(blank=True, null=True)),
                ('news_sports', models.FloatField(blank=True, null=True)),
                ('news_car', models.FloatField(blank=True, null=True)),
                ('news_finance', models.FloatField(blank=True, null=True)),
                ('news_funny', models.FloatField(blank=True, null=True)),
                ('news_military', models.FloatField(blank=True, null=True)),
                ('news_world', models.FloatField(blank=True, null=True)),
                ('news_fashion', models.FloatField(blank=True, null=True)),
                ('news_baby', models.FloatField(blank=True, null=True)),
                ('news_history', models.FloatField(blank=True, null=True)),
                ('news_food', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='news_comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
        migrations.AddField(
            model_name='news_comment',
            name='parent_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reply_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news_comment',
            name='root_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='root_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
