# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-02 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20180201_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pubtime']},
        ),
        migrations.AlterModelOptions(
            name='news_comment',
            options={'ordering': ['-comment_time']},
        ),
        migrations.RenameField(
            model_name='news_comment',
            old_name='date_created',
            new_name='comment_time',
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_baby',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_car',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_entertainment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_fashion',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_finance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_food',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_funny',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_game',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_history',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_military',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_society',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_sports',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_tech',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='news_tag_score',
            name='news_world',
            field=models.FloatField(default=0),
        ),
    ]
