# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-06 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20180202_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_predict',
            field=models.BooleanField(default=False),
        ),
    ]
