# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_is_predict'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_tag_score',
            name='news_baby',
        ),
        migrations.RemoveField(
            model_name='news_tag_score',
            name='news_car',
        ),
        migrations.RemoveField(
            model_name='news_tag_score',
            name='news_food',
        ),
        migrations.RemoveField(
            model_name='news_tag_score',
            name='news_funny',
        ),
        migrations.RemoveField(
            model_name='news_tag_score',
            name='news_history',
        ),
        migrations.RemoveField(
            model_name='news_tag_score',
            name='news_military',
        ),
        migrations.RemoveField(
            model_name='news_tag_score',
            name='news_world',
        ),
    ]
