# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20180304_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news_hot',
            options={'ordering': ['-score', '-pubtime']},
        ),
        migrations.AddField(
            model_name='news_hot',
            name='classification',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='news_hot',
            name='news',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='news.news'),
        ),
    ]
