# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20180305_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news_comment',
            name='root_user',
        ),
        migrations.AddField(
            model_name='news_comment',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news_comment',
            name='root_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='parent_user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, related_name='reply_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
