# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 11:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20180305_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='news.news'),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reply_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='news_comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
