# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20180306_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-count', '-date_created'],
            },
        ),
    ]
