# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-08 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180207_1625'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_tag',
            new_name='user_tag_score',
        ),
        migrations.AlterModelOptions(
            name='user_recommendation',
            options={'ordering': ['-date_created']},
        ),
    ]
