# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-04 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180208_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_similarity',
            name='similary_user',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
