# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180306_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar/default.jpg', null=True, upload_to='avatar/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
