# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 19:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_search_hot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_auto_20180306_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_cf_recommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=20)),
                ('pubtime', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCF', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pubtime'],
            },
        ),
        migrations.CreateModel(
            name='user_collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
