# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 21:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_cf_recommendation_user_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_search',
            name='keyword',
        ),
        migrations.AddField(
            model_name='user_search',
            name='key_words',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_search',
            name='content',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_search',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search', to=settings.AUTH_USER_MODEL),
        ),
    ]
